services:
  # Banco de Dados
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # API Monolito (Node + TS)
  api:
    build:
     context: .
     target: development
    container_name: node_api_dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Evita sobrescrever node_modules do container
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    command: npm run dev # Garante que rode o ts-node-dev ou nodemon
    depends_on:
      - mysql

  kong:
    image: kong:latest
    container_name: kong_gateway
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000" # Porta do Proxy (Tráfego vindo de fora)
      - "8443:8443" # Porta do Proxy SSL
      - "8001:8001" # Porta da Admin API (Somente leitura no DB-less)
    depends_on:
      - api

volumes:
  mysql_data:
