services:
  # Banco de Dados
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_DATABASE: webstore_catalogo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # API Monolito (Node + TS)
  api:
    build: .
    container_name: node_api_dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Evita sobrescrever node_modules do container
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=webstore_catalogo
    ports:
      - "3000:3000"
    command: npm run dev # Garante que rode o ts-node-dev ou nodemon
    depends_on:
      - mysql

volumes:
  mysql_data:
