services:
  # Banco de Dados
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Cache (Redis)
  redis:
    image: redis:alpine
    container_name: redis_dev
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # RabbitMQ (Mensageria)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_dev
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    ports:
      - "5672:5672"   # Porta do protocolo AMQP
      - "15672:15672" # Porta do Painel de Gerenciamento (Dashboard)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Monolito (Node + TS)
  api:
    build:
     context: .
     target: development
    container_name: node_api_dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_HOST=mysql
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
    command: >
      sh -c "
        until nc -z -v -w30 mysql 3306; do echo 'Aguardando MySQL...'; sleep 2; done
        until nc -z -v -w30 redis 6379; do echo 'Aguardando Redis...'; sleep 2; done
        until nc -z -v -w30 rabbitmq 5672; do echo 'Aguardando RabbitMQ...'; sleep 2; done
        npm run typeorm migration:run && npm run dev
      "
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  kong:
    image: kong:latest
    container_name: kong_gateway
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
    depends_on:
      - api

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch_dev
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_ENV=development
    volumes:
      - meili_data:/meili_data
  
  worker-search:
    build:
      context: .
      target: development
    container_name: node_worker_search
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_HOST=mysql
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - RABBITMQ_HOST=rabbitmq
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
    # O Worker não roda migrations, ele apenas consome a fila
    command: >
      sh -c "
        until nc -z -v -w30 mysql 3306; do echo 'Aguardando MySQL...'; sleep 2; done
        until nc -z -v -w30 rabbitmq 5672; do echo 'Aguardando RabbitMQ...'; sleep 2; done
        npm run worker
      "
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      meilisearch:
        condition: service_started

volumes:
  mysql_data:
  meili_data:
