openapi: 3.0.0
info:
  title: API de Categorias e Atributos
  version: 1.0.0

paths: {} # O Swagger exige essa seção, mesmo que vazia.

components:
  schemas:

    AttributeDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - name
      - created_at
      - updated_at

    CreateAttributeDTO:
      type: object
      properties:
        name:
          type: string
      required:
      - name

    UpdateAttributeDTO:
      type: object
      properties:
        name:
          type: string
      required:
      - name

    GetAllAttributesInputDTO:
      type: object
      properties:
        page:
          type: integer
          minimum: 1
        limit:
          type: integer
          minimum: 1
        name:
          type: string

    PaginatedAttributesDTO:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/AttributeDTO'
        total:
          type: integer
        page:
          type: integer
        limit:
          type: integer
      required:
      - items
      - total
      - page
      - limit

    CategoryDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        parent_id:
          type: string
          format: uuid
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - name
      - slug
      - created_at
      - updated_at

    CreateCategoryDTO:
      type: object
      properties:
        name:
          type: string
        parent_id:
          type: string
          format: uuid
          nullable: true
        slug:
          type: string
      required:
      - name

    UpdateCategoryDTO:
      type: object
      properties:
        name:
          type: string
      required:
      - name

    GetAllCategoriesInputDTO:
      type: object
      properties:
        name:
          type: string
        limit:
          type: integer
        page:
          type: integer

    PaginatedCategoriesDTO:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/CategoryDTO'
        total:
          type: integer
        page:
          type: integer
        limit:
          type: integer
      required:
      - items
      - total
      - page
      - limit

    CreateImageDTO:
      type: object
      required:
      - produto_id
      - url
      - ordem
      properties:
        produto_id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        url:
          type: string
          format: uri
          example: "https://exemplo.com"
        ordem:
          type: integer
          example: 1

    UpdateImageDTO:
      type: object
      required:
      - id
      properties:
        id:
          type: string
          format: uuid
        url:
          type: string
          format: uri
        ordem:
          type: integer

    ImageResponseDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        produto_id:
          type: string
          format: uuid
        url:
          type: string
          format: uri
        ordem:
          type: integer
        created_at:
          type: string
          format: date-time

    PaginatedImagesDTO:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ImageResponseDTO'
        total:
          type: integer
          example: 100
        page:
          type: integer
          example: 1

    CreateProductInputDto:
      type: object
      required:
      - name
      - description
      - category_id
      properties:
        name:
          type: string
        description:
          type: string
        category_id:
          type: string
          format: uuid

    ProductOutputDto:
      type: object
      required:
      - id
      - name
      - slug
      - description
      - category_id
      - created_at
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        images:
          type: array
          items:
            $ref: '#/components/schemas/ImageResponseDTO'
        category:
          $ref: '#/components/schemas/CategoryDTO'
        description:
          type: string
        category_id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time

    UpdateProductInputDto:
      type: object
      required:
      - id
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        category_id:
          type: string
          format: uuid
